go-app/routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Head Up: phoinfo will expose sensitive data!
// Route::get('/phpinfo', function () {
//     phpinfo();
// });

Route::get('/', function () {
    return view('home', ['page' => 'home']);
})->name('home');

Route::get('/react', function () {
  return view('home-react');
});

Route::get('/try', function () {
    dd(app()->routes->getRoutes());
});

// Confirm pages
Route::post('/aliasconfirm', 'AliasController@create')->name('aliasconfirm');
Route::post('/emailconfirm', 'PageController@contactSend')->name('emailconfirm');
Route::view('/reportconfirm', 'reportconfirm')->name('reportconfirm');

// Main pages
Route::get('/about', 'PageController@about')->name('about');
Route::get('/stats', 'StatsController@index')->name('stats');
Route::get('/faq', 'PageController@FAQ')->name('FAQ');
Route::get('/contact', 'PageController@contact')->name('contact');
Route::get('/profile', 'UserController@details')->name('profile');
Route::get('/me', 'UserController@me')->name('me');
Route::get('/moi', 'UserController@me')->name('moi');
Route::get('/reveal', 'PageController@revealInfo')->name('revealInfo');
Route::get('/extension', 'PageController@extension')->name('Web Extension');
Route::get('/design', 'PageController@design')->name('Logos');

// Browse
Route::get('/browse', 'BrowseController@index_datatable')->name('browse');
Route::get('/browsedt', 'BrowseController@index_datatable_cache')->name('browsedt');
Route::get('/browsedtnocache', 'BrowseController@index_datatable')->name('browsenocache');
Route::get('/browsedtajax', 'BrowseController@index_datatable_ajax')->name('browsedtajax');
Route::get('/browse/s/', 'BrowseController@search')->name('search');

// API
Route::get('/api', 'PageController@api')->name('api');
Route::get('/api/v1', 'PageController@api')->name('api');

// Specific pages
Route::get('/info/{alias}', 'AliasDetails@info')->name('info');
Route::get('/qr', 'QRController@qr')->name('qr');
Route::get('/qr/{alias}.{format}', 'QRController@qr_image')->name('qr_image');
Route::get('/qr/{alias}', 'QRController@qr_alias')->name('qr_alias');
Route::get('/edit/alias/{alias}', 'AliasController@edit')->name('edit/alias');
Route::post('/update/alias', 'AliasController@update')->name('update/alias');
Route::post('/update/owner', 'AliasController@updateOwner')->name('update/owner');
Route::get('/alias/confirm-delete/{alias}', 'AliasController@confirmDelete')->name('confirm-delete/alias');
Route::post('/alias/delete/{alias}', 'AliasController@delete')->name('delete/alias');
Route::get('/reveal/{alias}', function (App\Models\Alias $alias){
    return view('reveal', [
        'alias' => $alias->alias,
        'url'   => $alias->url->url
    ]);
});
Route::get('/report/{alias}', 'FlagsController@report')->middleware('auth');
Route::get('/token/generate', 'UserController@generateToken');
Route::get('/token/delete', 'UserController@deleteToken');

// Syndication Feed
Route::get('/feed', 'FeedController@index')->name('feed');
Route::permanentRedirect('/rss', '/feed');
Route::permanentRedirect('/atom', '/feed');

// Admin / backoffice
Route::group([
    'prefix' => 'admin-php',
    'middleware' => ['admin']
], function () {
    Route::get('/', 'AdminController@index')->name('admin');

    Route::get('aliases', 'AdminController@aliases')->name('admin-aliases');
    Route::get('alias/{alias}', 'AdminController@editAlias')->name('admin-edit-alias');
    Route::get('/alias/confirm-delete/{alias}', 'AdminController@confirmDelete')->name('alias/confirm-delete');
    Route::post('/alias/delete/{alias}', 'AdminController@deleteAlias')->name('delete/alias');
    Route::post('update/owner', 'AdminController@updateOwner')->name('admin-update-owner');
    Route::post('delete/owner', 'AdminController@deleteOwner')->name('admin-delete-owner');
    Route::post('update/{alias}', 'AdminController@updateAlias')->name('admin-update-alias');

    Route::get('flags', 'AdminController@flags')->name('admin-flags');
    Route::get('people', 'AdminController@people')->name('admin-people');

    Route::get('blacklist', 'AdminController@blacklist')->name('admin-blacklist');
    Route::post('blacklist/append', 'AdminController@appendToBlacklist')->name('admin-blacklist-append');
    Route::delete('blacklist/delete/{keyword}', 'AdminController@deleteFromBlacklist')->name('admin-blacklist-delete');

    Route::get('advanced', 'AdminController@advanced')->name('admin-advanced');
    Route::post('add/administrator', 'AdminController@addAdministrator')->name('admin-add-administrator');
    Route::get('jobs/reliability_test', 'AdminController@runReliabilityTest')->name('admin-reliability-test');
});

// React-Admin / backoffice
Route::group([
  'prefix' => 'admin',
  'middleware' => ['admin']
], function () {
  Route::get('/{path1?}/{path2?}', function () {
    return view('home-react');
  });
});

/*
 * ServiceNow magic redirect for INC, CHG, CIM, CTASK, OUT, KB, RITM, IDEA, PRB and SVC
 *
 * Manual Testing:
 *  - https://go-dev.epfl.ch/INC0441402
 *  - https://go-dev.epfl.ch/CHG0040706
 *  - https://go-dev.epfl.ch/CIM0001553
 *  - https://go-dev.epfl.ch/CTASK0019229
 *  - https://go-dev.epfl.ch/OUT0006519
 *  - https://go-dev.epfl.ch/KB0015277
 *  - https://go-dev.epfl.ch/bKB0015277
 *  - https://go-dev.epfl.ch/RITM0246550
 *  - https://go-dev.epfl.ch/IDEA0001152
 *  - https://go-dev.epfl.ch/PRB0040262
 *  - https://go-dev.epfl.ch/SVC0176
 *  - https://go-dev.epfl.ch/SCR0974766
 *  - https://go-dev.epfl.ch/RSK0000074 (https://support.epfl.ch/nav_to.do?uri=x_epfl2_audit_risk.do?sysparm_query=number=RSK0000074)
 *  - https://go-dev.epfl.ch/AUD0000001 (https://support.epfl.ch/nav_to.do?uri=x_epfl2_audit_report.do?sysparm_query=number=AUD0000001)
 *  - https://go-dev.epfl.ch/PRJ0044890 (https://support.epfl.ch/nav_to.do?uri=/pm_project.do?sysparm_query=number=PRJ0044890)
 *
 * ServiceNow doc:
 *   - https://docs.servicenow.com/bundle/paris-platform-user-interface/page/use/navigation/task/navigate-using-url.html
 *   - https://docs.servicenow.com/bundle/paris-platform-user-interface/page/use/navigation/reference/r_NavigatingByURLExamples.html
 */
$servicenow_url = 'https://support.epfl.ch'; // https://epfl.service-now.com
// magic-redirect for INCident.
Route::get(
    '/INC{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/incident.do?sysparm_query=number=INC' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for CHanGe.
Route::get(
    '/CHG{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/change_request.do?sysparm_query=number=CHG' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for CIM (Continuous IMprovement).
Route::get(
    '/CIM{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/sn_cim_register.do?sysparm_query=number=CIM' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for Change TASK.
Route::get(
    '/CTASK{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/change_task.do?sysparm_query=number=CTASK' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for TASK.
Route::get(
    '/TASK{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/sc_task.do?sysparm_query=number=TASK' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for OUTage.
Route::get(
    '/OUT{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/cmdb_ci_outage.do?sysparm_query=u_number=OUT' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for KnowledgeBase.
Route::get(
    '/KB{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/epfl?id=epfl_kb_article_view&sysparm_article=KB' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for KnowledgeBase (Backoffice), e.g. https://support.epfl.ch/nav_to.do?uri=%2Fkb_view.do%3Fsysparm_article%3DKB0012435
// https://support.epfl.ch/nav_to.do?uri=/kb_view.do&sysparm_article=KB0012435
// It appears that the help desk want to use short links inside
// Service Now itself and it somehow can't manage the link that add
// the left menu — backing off to http://support.epfl.ch/kb_view.do?sysparm_article=KB0012435 while I don't like it at all.
Route::get(
    '/bKB{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/kb_view.do?sysparm_article=KB' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for RITM.
Route::get(
    '/RITM{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/sc_req_item.do?sysparm_query=number=RITM' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for IDEA.
Route::get(
    '/IDEA{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/idea.do?sysparm_query=number=IDEA' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for PRoBlem.
Route::get(
    '/PRB{id}',
    function ( $id ) use ( $servicenow_url ) {
        return redirect( $servicenow_url . '/nav_to.do?uri=/problem.do?sysparm_query=number=PRB' . $id );
    }
)->where( 'id', '[0-9]{7}' );
// magic-redirect for PRoJect.
Route::get(
    '/PRJ{id}',
    function ( $id ) use ( $servicenow_url ) {
        https://support.epfl.ch/pm_project.do?sys_id=4f8164809764b1102f9976971153afbf

go-app/app/Http/Controllers/FeedController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Response;
use Illuminate\Support\Facades\Log;
use App\Models\Alias;

/**
 * This class create a Atom Syndication
 * See https://tools.ietf.org/html/rfc4287
 * See https://validator.w3.org/feed/docs/atom.html
 */
class FeedController extends Controller
{
    public $feed;

    public function index()
    {
        // Define the feed metadata
        $this->getFeedMetadata();
        $this->getFeedEntries();
        // Get the view's content
        $content = view('layouts.feed', ['feed' => $this->feed]);
        // Return the HTTP response with the content specifying the header's 
        // Content-Type to text/xml 
        // (see https://stackoverflow.com/a/3272572/960623)
        return response($content, 200)
                ->header('Content-Type', 'text/xml');
    }
    
    /**
     * Set the metadata elements of the feed
     **/
    private function getFeedMetadata()
    {
        $this->feed                = (object)[];
        $this->feed->title         = config('app.name') . '\'s syndication feed';
        $this->feed->link          = config('app.url') . 'feed';
        $this->feed->updated       = date('c');
        $this->feed->author        = (object)[];
        $this->feed->author->name  = config('app.name') . '\'s admins';
        $this->feed->author->email = 'go@groupes.epfl.ch';
        $this->feed->author->uri   = config('app.url') . 'contact';
        $this->feed->id            = 'urn:uuid:7d90b9a3-b584-4aae-ae76-db1b5823cf82';
    }
    
    /**
     * Set the entries elements of the feed
     **/
    private function getFeedEntries()
    {
        $this->feed->entries = Alias::public()
                                ->withCount('clicks')
                                ->leftJoin('urls', 'aliases.url_id', '=', 'urls.id')
                                ->orderby('aliases.created_at', 'DESC')
                                ->limit(30)
                                ->get();
    }
}

go-app/resources/views/layouts/app-full.blade.php
@extends('layouts.skeleton')
@section('body')
    <div class="main-container">
        @include('layouts.menu.mobile.menu')
        <div id="app-layout" class="container-full">
            <main class="py-4 pl-5 pr-5">
                @include('layouts.errors')
                @include('layouts.partials.announce')
                @yield('content')
            </main>
        </div>
    </div>
@endsection

go-app/resources/views/layouts/app-react.blade.php
@extends('layouts.skeleton-react')
@section('body')
    <div class="main-container">
        @include('layouts.menu.mobile.menu')
        <div id="app-layout" class="container">
            <main class="py-4">
                @include('layouts.errors')
                @include('layouts.partials.announce')
                @yield('content')
            </main>
        </div>
    </div>
@endsection

go-app/resources/views/layouts/app.blade.php
@extends('layouts.skeleton')
@section('body')
    <div class="main-container">
        @include('layouts.menu.mobile.menu')
        <div id="app-layout" class="container">
            <main class="py-4">
                @include('layouts.errors')
                @include('layouts.partials.announce')
                @yield('content')
            </main>
        </div>
    </div>
@endsection

go-app/resources/views/layouts/empty.blade.php
@if ($errors->any())
    @foreach ($errors->all() as $error)
        {{{$error}}}
    @endforeach
@endif
@yield('content')

go-app/resources/views/layouts/errors.blade.php
@if ($errors->any())
  <div id="errors">
    @foreach ($errors->all() as $error)
      <div class="error_message alert alert-danger alert-dismissible fade show" role="alert">
        <strong>Watch out !</strong> {{{$error}}}
        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
    @endforeach
  </div>
@endif

@if (session('status'))
    <div class="alert alert-success">
        {{ session('status') }}
    </div>
@endif

go-app/resources/views/layouts/feed.blade.php
<?xml version="1.0" encoding="utf-8"?>
<feed xmlns="http://www.w3.org/2005/Atom">

  <title>{{ $feed->title }}</title>
  <link href="{{ $feed->link }}"/>
  <updated>{{ $feed->updated }}</updated>
  <author>
    <name type="html">{{ $feed->author->name }}</name>
    <email>{{ $feed->author->email }}</email>
    <uri>{{ $feed->author->uri }}</uri>
  </author>
  <id>{{ $feed->id }}</id>

  @foreach ($feed->entries as $entry)
    @include('layouts.feedEntry')
  @endforeach
</feed>

go-app/resources/views/layouts/feedEntry.blade.php
  <entry>
    <title type="html">{{ config('app.url') }}{{ $entry->alias }} → {{{$entry->url->url}}}</title>
    <link href="{{ config('app.url') }}{{ $entry->alias }}"/>
    <id>tag:{{ config('app.url') }}{{ $entry->alias }}:@php echo sha1($entry->alias); @endphp</id>
    <updated>{{ $entry->updated_at }}</updated>
    <created>{{ $entry->created_at }}</created>
    <summary type="html">
      <![CDATA[
      The link <a href="{{ config('app.url') }}{{ $entry->alias }}">{{{$entry->url->url}}}</a> 
      has been shortened on {{ $entry->created_at }}.
      <br />
      Its alias is <b>{{ $entry->alias }}</b>.
      <br />
      It has been clicked {{ $entry->clicks_count }} times.
      <br />
      Please visit it here: <a href="{{ config('app.url') }}{{ $entry->alias }}">{{{$entry->url->url}}}</a>.
      <br /><hr />
      <a href="{{ config('app.url') }}">{{ config('app.name') }}</a> — EPFL URL shortener (<a href="{{ config('app.url') }}contact">contact</a>)
      ]]>
    </summary>
  </entry>

go-app/resources/views/layouts/footer.blade.php
<?php # https://epfl-si.github.io/elements/#/organisms/footer/light-dark-en/full ?>
<footer class="footer-light fixed-bottom d-none d-md-block" role="contentinfo">
  <div class="tlbx-component-footer-light-dark-en bg-dark">
    <div>&nbsp;
      <!-- poor man's space on Friday's night -->
    </div>
    <div class="row">
      <div class="col-xl-11 mx-xl-auto">
        <div class="row">
          <div class="col-6 mx-auto mx-md-0 mb-4 col-md-3 col-lg-2 text-center">
            <a href="/">
              <img src="/logo/GoEPFL_red.svg" style="height: 100px;" class="text-center" />
            </a>
          </div>
          <div class="col-md-9 col-lg-10">
            <div class="ml-md-2 ml-lg-5">
              <ul class="list-inline list-unstyled">
                <li class="list-inline-item text-white">Contact</li>
                <li class="list-inline-item text-gray-300 pl-3"><small>EPFL CH-1015 Lausanne</small></li>
                <li class="list-inline-item text-gray-300 pl-3"><small>+41 21 693 11 11</small></li>
              </ul>
              <p class="footer-light-socials">
                <small>Follow the EPFL on social media</small>
                <span>
                  <a href="https://www.facebook.com/epflcampus" class="social-icon social-icon-facebook social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-facebook"></use>
                    </svg>
                    <span class="sr-only">Follow us on Facebook.</span>
                  </a>
                  <a href="https://twitter.com/epfl" class="social-icon social-icon-twitter social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-twitter"></use>
                    </svg>
                    <span class="sr-only">Follow us on Twitter.</span>
                  </a>
                  <a href="http://instagram.com/epflcampus" class="social-icon social-icon-instagram social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-instagram"></use>
                    </svg>
                    <span class="sr-only">Follow us on Instagram.</span>
                  </a>
                  <a href="https://www.youtube.com/user/epflnews" class="social-icon social-icon-youtube social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-youtube"></use>
                    </svg>
                    <span class="sr-only">Follow us on Youtube.</span>
                  </a>
                  <a href="https://www.linkedin.com/school/epfl/" class="social-icon social-icon-linkedin social-icon-negative">
                    <svg class="icon" aria-hidden="true">
                      <use xlink:href="#icon-linkedin"></use>
                    </svg>
                    <span class="sr-only">Follow us on LinkedIn.</span>
                  </a>
                </span>
              </p>

              <div class="footer-legal">
                <div class="footer-legal-links">
                  <a href="https://epfl-si.github.io/elements/#/doc/accessibility.html">{{ __('Accessibility') }}</a>
                  <a href="https://www.epfl.ch/about/overview/overview/regulations-and-guidelines/">{{ __('Legals') }}</a>
                  <a href="{{ route('contact') }}">{{ __('Contact') }}</a>
                  <a href="https://gitlab.com/epfl-isasfsd/go-epfl">{{ __('Source code') }}</a>
                  <a href="https://gitlab.com/epfl-isasfsd/go-epfl/-/tags/{{ config('app.version') }}">version</a><small>:&nbsp;{{ config('app.version') }}</small>
                </div>
                <div>
                  <p>&copy; 2018-<?php echo date('Y') ?> {{ __('EPFL, all rights reserved') }}</p>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</footer>

go-app/resources/views/layouts/header.blade.php
{{-- From EPFL https://epfl-si.github.io/elements/#/organisms/header/light-fr/full --}}
<header role="banner" class="header header-light navbar-laravel" id="app-layout">
  <div class="drawer mr-3 mr-xl-0">
    <button class="drawer-toggle">
      <svg class="icon" aria-hidden="true"><use xlink:href="#icon-chevron-right"></use></svg>
    </button>
    <a href="//www.epfl.ch" class="drawer-link">
      <span class="text">
        Go to EPFL main site
      </span>
    </a>
  </div>

  <div class="header-light-content">
    <a class="logo" href="/">
      <img src="/svg/epfl-logo.svg" alt="Logo EPFL, École polytechnique fédérale de Lausanne" class="img-fluid">
    </a>
    <h1><acronyme title="EPFL URL Shortener">{{ config('app.name') }}</acronyme></h1>

    @include('layouts.menu.menu')

    @include('layouts.menu.mobile.search')
    @include('layouts.menu.partials.search')

    @include('layouts.menu.partials.user')

    @include('layouts.menu.mobile.burger')

  </div>
  @include('layouts.partials.ribbon')
</header>

go-app/resources/views/layouts/httperrors.blade.php
@extends('layouts.app')

@section('content')
  <div class="row">
    <div class="col-8">
      <h2>@yield('title')</h2>
    </div>
    <div class="col-4">
      <h2>@yield('code')</h2>
    </div>
  </div>
  <br />
  <div class="row">
    <div class="col-12">
      <p>
        @yield('message')
      </p>
      <p>
        The server returned the HTTP status code <b>@yield('code')</b> "@yield('title')".
        <br />
        You can have more information about this status code <a href="https://httpstatuses.com/@yield('code')" target="_blank">here</a>...
      </p>
      <p>
        If you think that should not have happened, please contact us <a href="/contact">here</a>. Otherwise, head back to the <a href="/">homepage</a>.
      </p>
    </div>
  </div>
@endsection

go-app/resources/views/layouts/skeleton-react.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <title>{{ config('app.name') }}</title>
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="alternate" type="application/atom+xml" title="{{ config('app.name') }}'s syndication feed" href="/feed">

    @include('layouts.partials.cookieconsent')

</head>

<body data-spy="scroll" data-target="#intermediate-nav" data-offset="0">

@include('layouts.header')

<!-- React root DOM -->
<div id="root" data-app-url="{{ config('app.url') }}">
</div>
@include('layouts.footer')
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@yield('javascript')
</body>

</html>

go-app/resources/views/layouts/skeleton.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">

<head>
    <title>{{ config('app.name') }}</title>
    <meta name="title" content="Go EPFL">
    <meta name="description" content="EPFL's URL shortener."/>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta charset="utf-8">
    <link rel="author" href="humans.txt" />

    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="180x180" href="/favicon/apple-touch-icon.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon/favicon-16x16.png">
    <link rel="manifest" href="/favicon/site.webmanifest">
    <link rel="mask-icon" href="/favicon/safari-pinned-tab.svg" color="#5bbad5">
    <link rel="shortcut icon" href="/favicon/favicon.ico">
    <meta name="msapplication-TileColor" content="#da532c">
    <meta name="msapplication-config" content="/favicon/browserconfig.xml">
    <meta name="theme-color" content="#ffffff">

    <!-- Open Graph / Facebook -->
    <meta name="og:type" content="website">
    <meta name="og:url" content="https://go.epfl.ch/">
    <meta name="og:title" content="Go EPFL">
    <meta name="og:description" content="EPFL's URL shortener.">
    <meta name="og:image" content="{{ url('/img/screenshots/screely-full-logged-transparent.png') }}">

    <!-- Twitter -->
    <meta name="twitter:card" content="summary_large_image">
    <meta name="twitter:url" content="https://go.epfl.ch/">
    <meta name="twitter:site" content="@goepflbot">
    <meta name="twitter:creator" content="@ponsfrilus">
    <meta name="twitter:title" content="Go EPFL">
    <meta name="twitter:description" content="EPFL's URL shortener.">
    <meta name="twitter:image" content="{{ url('/img/screenshots/screely-full-logged-transparent.png') }}">


    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">
    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet" type="text/css">
    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
    <link rel="alternate" type="application/atom+xml" title="{{ config('app.name') }}'s syndication feed" href="/feed">

    @include('layouts.partials.cookieconsent')

</head>

<body data-spy="scroll" data-target="#intermediate-nav" data-offset="0">

@include('layouts.header')
@yield('body')
@include('layouts.footer')
<!-- Scripts -->
<script src="{{ asset('js/app.js') }}"></script>
@yield('javascript')
</body>

</html>